{% set name = "grits" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/grits/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c779676e887e8106740b4b4add1b3f36d174d77a7b7d55d90a78cd054139282b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8, <3.12
    - pip
  run:
    - python >=3.8
    - cmeutils >=1.2.0
    - rowan
    - ele
    - freud =2.13.2
    - gsd >=3.0
    - mbuild >=0.17.0
    - numpy
    - openbabel
    - rdkit
    - py3Dmol

test:
  imports:
    - grits
  requires:
    - pip

about:
  home: https://github.com/cmelab/grits
  summary: 'A toolkit for working with coarse-grain systems'
  description: |
    GRiTS is a toolkit for working with coarse-grain systems. It uses 
    mBuild <https://mbuild.mosdef.org> to build up molecules and 
    SMILES <https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html>
    chemical grammar to facilitate the mapping from fine-to-coarse and 
    coarse-to-fine.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  doc_url: https://grits.readthedocs.io
  dev_url: https://github.com/cmelab/grits

extra:
  recipe-maintainers:
    - jennyfothergill
    - chrisjonesBSU
    - marjanalbouye
