{% set name = "grits" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/cmelab/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioningit
  run:
    - python >={{ python_min }}
    - cmeutils >=1.3.0
    - rowan
    - ele
    - freud >=3.0
    - gsd >=3.0
    - mbuild >=0.17.0
    - numpy
    - openbabel
    - py3Dmol

test:
  imports:
    - grits
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - python run_test.py {{ version }}

about:
  home: https://github.com/cmelab/grits
  summary: 'A toolkit for working with coarse-grain systems'
  description: |
    GRiTS is a toolkit for working with coarse-grain systems. It uses 
    mBuild <https://mbuild.mosdef.org> to build up molecules and 
    SMILES <https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html>
    chemical grammar to facilitate the mapping from fine-to-coarse and 
    coarse-to-fine.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  doc_url: https://grits.readthedocs.io
  dev_url: https://github.com/cmelab/grits

extra:
  recipe-maintainers:
    - marjanalbooyeh
    - jennyfothergill
    - chrisjonesBSU
